// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using smart_meter.Data.Context;

#nullable disable

namespace smart_meter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("smart_meter.Data.Entities.Arrear", b =>
                {
                    b.Property<long>("Arrearid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("arrearid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Arrearid"));

                    b.Property<string>("Arreartype")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("arreartype");

                    b.Property<long>("Billid")
                        .HasColumnType("bigint")
                        .HasColumnName("billid");

                    b.Property<long>("Consumerid")
                        .HasColumnType("bigint")
                        .HasColumnName("consumerid");

                    b.Property<string>("Paidstatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("paidstatus")
                        .HasDefaultValueSql("'Unpaid'::character varying");

                    b.HasKey("Arrearid")
                        .HasName("arrears_pkey");

                    b.HasIndex("Consumerid");

                    b.HasIndex(new[] { "Billid" }, "arrears_billid_key")
                        .IsUnique();

                    b.ToTable("arrears", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Bill", b =>
                {
                    b.Property<long>("Billid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("billid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Billid"));

                    b.Property<decimal>("Baseamount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("baseamount");

                    b.Property<DateOnly>("Billingperiodend")
                        .HasColumnType("date")
                        .HasColumnName("billingperiodend");

                    b.Property<DateOnly>("Billingperiodstart")
                        .HasColumnType("date")
                        .HasColumnName("billingperiodstart");

                    b.Property<long>("Consumerid")
                        .HasColumnType("bigint")
                        .HasColumnName("consumerid");

                    b.Property<DateTime?>("Discdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("discdate");

                    b.Property<DateOnly>("Duedate")
                        .HasColumnType("date")
                        .HasColumnName("duedate");

                    b.Property<DateTime>("Generatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("generatedat")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("Ispaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ispaid");

                    b.Property<string>("Meterserialno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("meterserialno");

                    b.Property<DateOnly?>("Paymentdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("paymentdate")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<decimal>("Taxamount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxamount");

                    b.Property<decimal?>("Totalamount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("totalamount")
                        .HasComputedColumnSql("(baseamount + taxamount)", true);

                    b.Property<decimal>("Totalunitsconsumed")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("totalunitsconsumed");

                    b.HasKey("Billid")
                        .HasName("bill_pkey");

                    b.HasIndex("Consumerid");

                    b.HasIndex("Meterserialno");

                    b.ToTable("bill", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.ConnectionRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RequestId"));

                    b.Property<long?>("ActionBy")
                        .HasColumnType("bigint")
                        .HasColumnName("action_by");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<long?>("ConsumerId")
                        .HasColumnType("bigint")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("request_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("RequestId");

                    b.HasIndex("ActionBy");

                    b.HasIndex("ConsumerId");

                    b.ToTable("connection_request", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Consumer", b =>
                {
                    b.Property<long>("Consumerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("consumerid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Consumerid"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Createdby")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("createdby")
                        .HasDefaultValueSql("'system'::character varying");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Orgunitid")
                        .HasColumnType("integer")
                        .HasColumnName("orgunitid");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("photo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<int>("Tariffid")
                        .HasColumnType("integer")
                        .HasColumnName("tariffid");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("Updatedby")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updatedby");

                    b.HasKey("Consumerid")
                        .HasName("consumer_pkey");

                    b.HasIndex("Orgunitid");

                    b.HasIndex("Tariffid");

                    b.ToTable("consumer", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Consumeraddress", b =>
                {
                    b.Property<long>("Addressid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("addressid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Addressid"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<long>("Consumerid")
                        .HasColumnType("bigint")
                        .HasColumnName("consumerid");

                    b.Property<string>("Houseno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("houseno");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.HasKey("Addressid")
                        .HasName("consumeraddress_pkey");

                    b.HasIndex(new[] { "Consumerid" }, "consumeraddress_consumerid_key")
                        .IsUnique();

                    b.ToTable("consumeraddress", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Meter", b =>
                {
                    b.Property<string>("Meterserialno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("meterserialno");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<long?>("Consumerid")
                        .HasColumnType("bigint")
                        .HasColumnName("consumerid");

                    b.Property<string>("Firmware")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firmware");

                    b.Property<string>("Iccid")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("iccid");

                    b.Property<string>("Imsi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("imsi");

                    b.Property<DateTime>("Installtsutc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("installtsutc");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.HasKey("Meterserialno")
                        .HasName("meter_pkey");

                    b.HasIndex("Consumerid");

                    b.ToTable("meter", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Meterreading", b =>
                {
                    b.Property<long>("Readingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("readingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Readingid"));

                    b.Property<decimal>("Current")
                        .HasPrecision(7, 3)
                        .HasColumnType("numeric(7,3)")
                        .HasColumnName("current");

                    b.Property<decimal>("Energyconsumed")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("energyconsumed");

                    b.Property<string>("Meterserialno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("meterserialno");

                    b.Property<DateTime>("Readingdatetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("readingdatetime");

                    b.Property<decimal>("Voltage")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("voltage");

                    b.HasKey("Readingid")
                        .HasName("meterreadings_pkey");

                    b.HasIndex("Meterserialno");

                    b.ToTable("meterreadings", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Orgunit", b =>
                {
                    b.Property<int>("Orgunitid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orgunitid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orgunitid"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Parentid")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Orgunitid")
                        .HasName("orgunit_pkey");

                    b.HasIndex("Parentid");

                    b.HasIndex(new[] { "Type" }, "idx_orgunit_type");

                    b.ToTable("orgunit", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Tariff", b =>
                {
                    b.Property<int>("Tariffid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tariffid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Tariffid"));

                    b.Property<decimal>("Baserate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("baserate");

                    b.Property<DateOnly>("Effectivefrom")
                        .HasColumnType("date")
                        .HasColumnName("effectivefrom");

                    b.Property<DateOnly?>("Effectiveto")
                        .HasColumnType("date")
                        .HasColumnName("effectiveto");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Taxrate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("taxrate");

                    b.HasKey("Tariffid")
                        .HasName("tariff_pkey");

                    b.HasIndex(new[] { "Effectivefrom" }, "idx_tariff_effectivefrom");

                    b.ToTable("tariff", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Tariffslab", b =>
                {
                    b.Property<int>("Tariffslabid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tariffslabid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Tariffslabid"));

                    b.Property<decimal>("Fromkwh")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("fromkwh");

                    b.Property<bool?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<decimal>("Rateperkwh")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rateperkwh");

                    b.Property<int>("Tariffid")
                        .HasColumnType("integer")
                        .HasColumnName("tariffid");

                    b.Property<decimal>("Tokwh")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("tokwh");

                    b.HasKey("Tariffslabid")
                        .HasName("tariffslab_pkey");

                    b.HasIndex("Tariffid");

                    b.ToTable("tariffslab", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Tarrifdetail", b =>
                {
                    b.Property<int>("Tarrifdetailid")
                        .HasColumnType("integer")
                        .HasColumnName("tarrifdetailid");

                    b.Property<int>("Tariffslabid")
                        .HasColumnType("integer")
                        .HasColumnName("tariffslabid");

                    b.Property<int>("Tarrifid")
                        .HasColumnType("integer")
                        .HasColumnName("tarrifid");

                    b.Property<int>("Todruleid")
                        .HasColumnType("integer")
                        .HasColumnName("todruleid");

                    b.HasKey("Tarrifdetailid")
                        .HasName("tarrifdetails_pkey");

                    b.HasIndex("Tariffslabid");

                    b.HasIndex("Tarrifid");

                    b.HasIndex("Todruleid");

                    b.ToTable("tarrifdetails", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Todrule", b =>
                {
                    b.Property<int>("Todruleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("todruleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Todruleid"));

                    b.Property<TimeOnly>("Endtime")
                        .HasPrecision(0)
                        .HasColumnType("time(0) without time zone")
                        .HasColumnName("endtime");

                    b.Property<bool?>("Isdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Rateperkwh")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rateperkwh");

                    b.Property<TimeOnly>("Starttime")
                        .HasPrecision(0)
                        .HasColumnType("time(0) without time zone")
                        .HasColumnName("starttime");

                    b.Property<int>("Tariffid")
                        .HasColumnType("integer")
                        .HasColumnName("tariffid");

                    b.HasKey("Todruleid")
                        .HasName("todrule_pkey");

                    b.HasIndex("Tariffid");

                    b.HasIndex(new[] { "Name" }, "idx_tod_name");

                    b.ToTable("todrule", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.User", b =>
                {
                    b.Property<long>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Userid"));

                    b.Property<string>("Displayname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("displayname");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failedlogincount");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("LastFailedLoginUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastfailedloginutc");

                    b.Property<DateTime?>("Lastloginutc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastloginutc");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lockoutendutc");

                    b.Property<byte[]>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Userid")
                        .HasName("User_pkey");

                    b.HasIndex(new[] { "Username" }, "User_username_key")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Arrear", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Bill", "Bill")
                        .WithOne("Arrear")
                        .HasForeignKey("smart_meter.Data.Entities.Arrear", "Billid")
                        .IsRequired()
                        .HasConstraintName("arrears_billid_fkey");

                    b.HasOne("smart_meter.Data.Entities.Consumer", "Consumer")
                        .WithMany("Arrears")
                        .HasForeignKey("Consumerid")
                        .IsRequired()
                        .HasConstraintName("arrears_consumerid_fkey");

                    b.Navigation("Bill");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Bill", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Consumer", "Consumer")
                        .WithMany("Bills")
                        .HasForeignKey("Consumerid")
                        .IsRequired()
                        .HasConstraintName("bill_consumerid_fkey");

                    b.HasOne("smart_meter.Data.Entities.Meter", "MeterserialnoNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("Meterserialno")
                        .IsRequired()
                        .HasConstraintName("bill_meterserialno_fkey");

                    b.Navigation("Consumer");

                    b.Navigation("MeterserialnoNavigation");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.ConnectionRequest", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.User", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionBy");

                    b.HasOne("smart_meter.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId");

                    b.Navigation("ActionByUser");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Consumer", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Orgunit", "Orgunit")
                        .WithMany("Consumers")
                        .HasForeignKey("Orgunitid")
                        .IsRequired()
                        .HasConstraintName("consumer_orgunitid_fkey");

                    b.HasOne("smart_meter.Data.Entities.Tariff", "Tariff")
                        .WithMany("Consumers")
                        .HasForeignKey("Tariffid")
                        .IsRequired()
                        .HasConstraintName("consumer_tariffid_fkey");

                    b.Navigation("Orgunit");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Consumeraddress", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Consumer", "Consumer")
                        .WithOne("Consumeraddress")
                        .HasForeignKey("smart_meter.Data.Entities.Consumeraddress", "Consumerid")
                        .IsRequired()
                        .HasConstraintName("consumeraddress_consumerid_fkey");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Meter", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Consumer", "Consumer")
                        .WithMany("Meters")
                        .HasForeignKey("Consumerid")
                        .HasConstraintName("meter_consumerid_fkey");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Meterreading", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Meter", "MeterserialnoNavigation")
                        .WithMany("Meterreadings")
                        .HasForeignKey("Meterserialno")
                        .IsRequired()
                        .HasConstraintName("meterreadings_meterserialno_fkey");

                    b.Navigation("MeterserialnoNavigation");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Orgunit", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Orgunit", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("Parentid")
                        .HasConstraintName("orgunit_parentid_fkey");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Tariffslab", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Tariff", "Tariff")
                        .WithMany("Tariffslabs")
                        .HasForeignKey("Tariffid")
                        .IsRequired()
                        .HasConstraintName("tariffslab_tariffid_fkey");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Tarrifdetail", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Tariffslab", "Tariffslab")
                        .WithMany("Tarrifdetails")
                        .HasForeignKey("Tariffslabid")
                        .IsRequired()
                        .HasConstraintName("tarrifdetails_tariffslabid_fkey");

                    b.HasOne("smart_meter.Data.Entities.Tariff", "Tarrif")
                        .WithMany("Tarrifdetails")
                        .HasForeignKey("Tarrifid")
                        .IsRequired()
                        .HasConstraintName("tarrifdetails_tarrifid_fkey");

                    b.HasOne("smart_meter.Data.Entities.Todrule", "Todrule")
                        .WithMany("Tarrifdetails")
                        .HasForeignKey("Todruleid")
                        .IsRequired()
                        .HasConstraintName("tarrifdetails_todruleid_fkey");

                    b.Navigation("Tariffslab");

                    b.Navigation("Tarrif");

                    b.Navigation("Todrule");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Todrule", b =>
                {
                    b.HasOne("smart_meter.Data.Entities.Tariff", "Tariff")
                        .WithMany("Todrules")
                        .HasForeignKey("Tariffid")
                        .IsRequired()
                        .HasConstraintName("todrule_tariffid_fkey");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Bill", b =>
                {
                    b.Navigation("Arrear");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Consumer", b =>
                {
                    b.Navigation("Arrears");

                    b.Navigation("Bills");

                    b.Navigation("Consumeraddress");

                    b.Navigation("Meters");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Meter", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Meterreadings");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Orgunit", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Tariff", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("Tariffslabs");

                    b.Navigation("Tarrifdetails");

                    b.Navigation("Todrules");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Tariffslab", b =>
                {
                    b.Navigation("Tarrifdetails");
                });

            modelBuilder.Entity("smart_meter.Data.Entities.Todrule", b =>
                {
                    b.Navigation("Tarrifdetails");
                });
#pragma warning restore 612, 618
        }
    }
}
